version: '3'

services:
  app:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    command: python src/main.py

  test:
    build: .
    volumes:
      - .:/app
    command: pytest -xvs tests/